### ISSUE TITLE
Could not resolve 'archive.ubuntu.com' - cidr 172.17.0.0/16 instead of 172.18.0.0/16

### ISSUE THREAD

**Issue by trompx** [diefans/ferment#2]
Hello,

My iptables are generated with ferm, I use ferment to get docker iptables and run docker with --iptables=false.

I noticed I could not build image anymore, getting the following errors :

```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip_1.5.4-1ubuntu3_all.deb  Could not resolve 'archive.ubuntu.com'
    Could not resolve 'archive.ubuntu.com'
```

I noticed that when removeing --iptables=false and restarting docker, my iptables rules had

```
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
```

while when I was generating them with ferm + ferment, I got :

```
-A POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE
```

Do you know if there is a way to automatically get the correct cidr ? For now I just add in my ferm.conf file the following :

```
domain $domains table nat {
  chain POSTROUTING {
    saddr 172.17.0.0/16 outerface !docker0 MASQUERADE;
  }
}
```

Is there a way to set the cidr value on the line :

```
@include '/usr/local/bin/ferment docker config|';
```

?

Thank you and thanks for sharing ferment !

**Comment by diefans** [comment]
I have updated the readme...

You may already choose your cidr and interface.

`ferment docker --cidr 172.17.0.0/16 --interface docker0 config`

**Comment by trompx** [comment]
Thanks a lot for the fast answer ! :)
