### ISSUE TITLE
ERROR: unable to insert jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -I FORWARD -j DOCKER-ISOLATION: iptables v1.6.0: Couldn't load target `DOCKER-ISOLATION':No such file or directory

### ISSUE THREAD

**Issue by strarsis** [diefans/ferment#8]
ferm was restarted with the ferment invocation included.

Trying to start a docker container results in error message:
````
ERROR: unable to insert jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -I FORWARD -j DOCKER-ISOLATION: iptables v1.6.0: Couldn't load target `DOCKER-ISOLATION':No such file or directory
````

Docker has to be restarted to let it set up the firewall rules anew - 
but the extra issue that some ports aren't reachable from the outside isn't fixed by this.

System:
- ferm 2.2
- Ubuntu 16.04.2 LTS
- Docker version 17.03.0-ce, build 60ccb22

**Comment by diefans** [comment]
to be honest, I have no time to investigate this issue for the next months... If you have a PR I will quasi-automatic merge it...

**Comment by strarsis** [comment]
Closed by PR https://github.com/diefans/ferment/pull/9.
